// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccessConfigInitParameters struct {

	// Virtual Private Cloud (VPC) subnets where IP addresses for the Kafka cluster are allocated. To make the cluster available in a VPC, you must specify at least one network_configs block. Max of 10 subnets per cluster. Additional subnets may be specified with additional network_configs blocks.
	// Structure is documented below.
	NetworkConfigs []NetworkConfigsInitParameters `json:"networkConfigs,omitempty" tf:"network_configs,omitempty"`
}

type AccessConfigObservation struct {

	// Virtual Private Cloud (VPC) subnets where IP addresses for the Kafka cluster are allocated. To make the cluster available in a VPC, you must specify at least one network_configs block. Max of 10 subnets per cluster. Additional subnets may be specified with additional network_configs blocks.
	// Structure is documented below.
	NetworkConfigs []NetworkConfigsObservation `json:"networkConfigs,omitempty" tf:"network_configs,omitempty"`
}

type AccessConfigParameters struct {

	// Virtual Private Cloud (VPC) subnets where IP addresses for the Kafka cluster are allocated. To make the cluster available in a VPC, you must specify at least one network_configs block. Max of 10 subnets per cluster. Additional subnets may be specified with additional network_configs blocks.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	NetworkConfigs []NetworkConfigsParameters `json:"networkConfigs" tf:"network_configs,omitempty"`
}

type CapacityConfigInitParameters struct {

	// The memory to provision for the cluster in bytes. The value must be between 1 GiB and 8 GiB per vCPU. Ex. 1024Mi, 4Gi.
	MemoryBytes *string `json:"memoryBytes,omitempty" tf:"memory_bytes,omitempty"`

	// The number of vCPUs to provision for the cluster. The minimum is 3.
	VcpuCount *string `json:"vcpuCount,omitempty" tf:"vcpu_count,omitempty"`
}

type CapacityConfigObservation struct {

	// The memory to provision for the cluster in bytes. The value must be between 1 GiB and 8 GiB per vCPU. Ex. 1024Mi, 4Gi.
	MemoryBytes *string `json:"memoryBytes,omitempty" tf:"memory_bytes,omitempty"`

	// The number of vCPUs to provision for the cluster. The minimum is 3.
	VcpuCount *string `json:"vcpuCount,omitempty" tf:"vcpu_count,omitempty"`
}

type CapacityConfigParameters struct {

	// The memory to provision for the cluster in bytes. The value must be between 1 GiB and 8 GiB per vCPU. Ex. 1024Mi, 4Gi.
	// +kubebuilder:validation:Optional
	MemoryBytes *string `json:"memoryBytes" tf:"memory_bytes,omitempty"`

	// The number of vCPUs to provision for the cluster. The minimum is 3.
	// +kubebuilder:validation:Optional
	VcpuCount *string `json:"vcpuCount" tf:"vcpu_count,omitempty"`
}

type ClusterInitParameters struct {

	// A capacity configuration of a Kafka cluster.
	// Structure is documented below.
	CapacityConfig *CapacityConfigInitParameters `json:"capacityConfig,omitempty" tf:"capacity_config,omitempty"`

	// The ID to use for the cluster, which will become the final component of the cluster's name. The ID must be 1-63 characters long, and match the regular expression [a-z]([-a-z0-9]*[a-z0-9])? to comply with RFC 1035. This value is structured like: my-cluster-id.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Configuration properties for a Kafka cluster deployed to Google Cloud Platform.
	// Structure is documented below.
	GCPConfig *GCPConfigInitParameters `json:"gcpConfig,omitempty" tf:"gcp_config,omitempty"`

	// List of label KEY=VALUE pairs to add. Keys must start with a lowercase character and contain only hyphens (-), underscores ( ), lowercase characters, and numbers. Values must contain only hyphens (-), underscores ( ), lowercase characters, and numbers.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Defines rebalancing behavior of a Kafka cluster.
	// Structure is documented below.
	RebalanceConfig *RebalanceConfigInitParameters `json:"rebalanceConfig,omitempty" tf:"rebalance_config,omitempty"`
}

type ClusterObservation struct {

	// A capacity configuration of a Kafka cluster.
	// Structure is documented below.
	CapacityConfig *CapacityConfigObservation `json:"capacityConfig,omitempty" tf:"capacity_config,omitempty"`

	// The ID to use for the cluster, which will become the final component of the cluster's name. The ID must be 1-63 characters long, and match the regular expression [a-z]([-a-z0-9]*[a-z0-9])? to comply with RFC 1035. This value is structured like: my-cluster-id.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The time when the cluster was created.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// Configuration properties for a Kafka cluster deployed to Google Cloud Platform.
	// Structure is documented below.
	GCPConfig *GCPConfigObservation `json:"gcpConfig,omitempty" tf:"gcp_config,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/clusters/{{cluster_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of label KEY=VALUE pairs to add. Keys must start with a lowercase character and contain only hyphens (-), underscores ( ), lowercase characters, and numbers. Values must contain only hyphens (-), underscores ( ), lowercase characters, and numbers.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// ID of the location of the Kafka resource. See https://cloud.google.com/managed-kafka/docs/locations for a list of supported locations.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Defines rebalancing behavior of a Kafka cluster.
	// Structure is documented below.
	RebalanceConfig *RebalanceConfigObservation `json:"rebalanceConfig,omitempty" tf:"rebalance_config,omitempty"`

	// The current state of the cluster. Possible values: STATE_UNSPECIFIED, CREATING, ACTIVE, DELETING.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// The time when the cluster was last updated.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type ClusterParameters struct {

	// A capacity configuration of a Kafka cluster.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	CapacityConfig *CapacityConfigParameters `json:"capacityConfig,omitempty" tf:"capacity_config,omitempty"`

	// The ID to use for the cluster, which will become the final component of the cluster's name. The ID must be 1-63 characters long, and match the regular expression [a-z]([-a-z0-9]*[a-z0-9])? to comply with RFC 1035. This value is structured like: my-cluster-id.
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Configuration properties for a Kafka cluster deployed to Google Cloud Platform.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	GCPConfig *GCPConfigParameters `json:"gcpConfig,omitempty" tf:"gcp_config,omitempty"`

	// List of label KEY=VALUE pairs to add. Keys must start with a lowercase character and contain only hyphens (-), underscores ( ), lowercase characters, and numbers. Values must contain only hyphens (-), underscores ( ), lowercase characters, and numbers.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// ID of the location of the Kafka resource. See https://cloud.google.com/managed-kafka/docs/locations for a list of supported locations.
	// +kubebuilder:validation:Required
	Location *string `json:"location" tf:"location,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Defines rebalancing behavior of a Kafka cluster.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	RebalanceConfig *RebalanceConfigParameters `json:"rebalanceConfig,omitempty" tf:"rebalance_config,omitempty"`
}

type GCPConfigInitParameters struct {

	// The configuration of access to the Kafka cluster.
	// Structure is documented below.
	AccessConfig *AccessConfigInitParameters `json:"accessConfig,omitempty" tf:"access_config,omitempty"`

	// The Cloud KMS Key name to use for encryption. The key must be located in the same region as the cluster and cannot be changed. Must be in the format projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/kms/v1beta2.CryptoKey
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	KMSKey *string `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`

	// Reference to a CryptoKey in kms to populate kmsKey.
	// +kubebuilder:validation:Optional
	KMSKeyRef *v1.Reference `json:"kmsKeyRef,omitempty" tf:"-"`

	// Selector for a CryptoKey in kms to populate kmsKey.
	// +kubebuilder:validation:Optional
	KMSKeySelector *v1.Selector `json:"kmsKeySelector,omitempty" tf:"-"`
}

type GCPConfigObservation struct {

	// The configuration of access to the Kafka cluster.
	// Structure is documented below.
	AccessConfig *AccessConfigObservation `json:"accessConfig,omitempty" tf:"access_config,omitempty"`

	// The Cloud KMS Key name to use for encryption. The key must be located in the same region as the cluster and cannot be changed. Must be in the format projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY.
	KMSKey *string `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`
}

type GCPConfigParameters struct {

	// The configuration of access to the Kafka cluster.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	AccessConfig *AccessConfigParameters `json:"accessConfig" tf:"access_config,omitempty"`

	// The Cloud KMS Key name to use for encryption. The key must be located in the same region as the cluster and cannot be changed. Must be in the format projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/kms/v1beta2.CryptoKey
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	KMSKey *string `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`

	// Reference to a CryptoKey in kms to populate kmsKey.
	// +kubebuilder:validation:Optional
	KMSKeyRef *v1.Reference `json:"kmsKeyRef,omitempty" tf:"-"`

	// Selector for a CryptoKey in kms to populate kmsKey.
	// +kubebuilder:validation:Optional
	KMSKeySelector *v1.Selector `json:"kmsKeySelector,omitempty" tf:"-"`
}

type NetworkConfigsInitParameters struct {

	// Name of the VPC subnet from which the cluster is accessible. Both broker and bootstrap server IP addresses and DNS entries are automatically created in the subnet. There can only be one subnet per network, and the subnet must be located in the same region as the cluster. The project may differ. The name of the subnet must be in the format projects/PROJECT_ID/regions/REGION/subnetworks/SUBNET.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type NetworkConfigsObservation struct {

	// Name of the VPC subnet from which the cluster is accessible. Both broker and bootstrap server IP addresses and DNS entries are automatically created in the subnet. There can only be one subnet per network, and the subnet must be located in the same region as the cluster. The project may differ. The name of the subnet must be in the format projects/PROJECT_ID/regions/REGION/subnetworks/SUBNET.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type NetworkConfigsParameters struct {

	// Name of the VPC subnet from which the cluster is accessible. Both broker and bootstrap server IP addresses and DNS entries are automatically created in the subnet. There can only be one subnet per network, and the subnet must be located in the same region as the cluster. The project may differ. The name of the subnet must be in the format projects/PROJECT_ID/regions/REGION/subnetworks/SUBNET.
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet" tf:"subnet,omitempty"`
}

type RebalanceConfigInitParameters struct {

	// The rebalance behavior for the cluster. When not specified, defaults to NO_REBALANCE. Possible values: MODE_UNSPECIFIED, NO_REBALANCE, AUTO_REBALANCE_ON_SCALE_UP.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type RebalanceConfigObservation struct {

	// The rebalance behavior for the cluster. When not specified, defaults to NO_REBALANCE. Possible values: MODE_UNSPECIFIED, NO_REBALANCE, AUTO_REBALANCE_ON_SCALE_UP.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

type RebalanceConfigParameters struct {

	// The rebalance behavior for the cluster. When not specified, defaults to NO_REBALANCE. Possible values: MODE_UNSPECIFIED, NO_REBALANCE, AUTO_REBALANCE_ON_SCALE_UP.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API. A Managed Service for Apache Kafka cluster.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.capacityConfig) || (has(self.initProvider) && has(self.initProvider.capacityConfig))",message="spec.forProvider.capacityConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.gcpConfig) || (has(self.initProvider) && has(self.initProvider.gcpConfig))",message="spec.forProvider.gcpConfig is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
